//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3607
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGrep.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GGrep.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &amp;Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BTN_TEXT_CANCEL {
            get {
                return ResourceManager.GetString("BTN_TEXT_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BTN_TEXT_SEARCH {
            get {
                return ResourceManager.GetString("BTN_TEXT_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Csv File(*.csv)|*.csv|All File(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FILE_FILTER {
            get {
                return ResourceManager.GetString("FILE_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   new.csv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FILE_NEM_NAME {
            get {
                return ResourceManager.GetString("FILE_NEM_NAME", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap minus {
            get {
                object obj = ResourceManager.GetObject("minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Please input the keyword. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_ERROR_01 {
            get {
                return ResourceManager.GetString("MSG_ERROR_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please specify an existing folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_ERROR_02 {
            get {
                return ResourceManager.GetString("MSG_ERROR_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please specify an existing encoding. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_ERROR_03 {
            get {
                return ResourceManager.GetString("MSG_ERROR_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Regex String. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_ERROR_04 {
            get {
                return ResourceManager.GetString("MSG_ERROR_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nothing to Save. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_ERROR_05 {
            get {
                return ResourceManager.GetString("MSG_ERROR_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You should run as Administrator to do this action. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_ERROR_06 {
            get {
                return ResourceManager.GetString("MSG_ERROR_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your Csv File has Saved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_SAVED {
            get {
                return ResourceManager.GetString("MSG_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancelled. Found {0} Places in {1} ms. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_STATUS_CANCELED {
            get {
                return ResourceManager.GetString("MSG_STATUS_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done. Found {0} Places in {1} ms. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_STATUS_FINISHED {
            get {
                return ResourceManager.GetString("MSG_STATUS_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ({0}/{1}) Searching...    Now {2} hits に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_STATUS_RUNNING {
            get {
                return ResourceManager.GetString("MSG_STATUS_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Analyzing Directories ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_STATUS_STARTED {
            get {
                return ResourceManager.GetString("MSG_STATUS_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_TITLE_01 {
            get {
                return ResourceManager.GetString("MSG_TITLE_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Success に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_TITLE_02 {
            get {
                return ResourceManager.GetString("MSG_TITLE_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_TITLE_03 {
            get {
                return ResourceManager.GetString("MSG_TITLE_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you like to cancel it ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_WARN_01 {
            get {
                return ResourceManager.GetString("MSG_WARN_01", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Search_files_128 {
            get {
                object obj = ResourceManager.GetObject("Search_files_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
