//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGrep.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GGrep.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string BTN_TEXT_CANCEL {
            get {
                return ResourceManager.GetString("BTN_TEXT_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;earch.
        /// </summary>
        internal static string BTN_TEXT_SEARCH {
            get {
                return ResourceManager.GetString("BTN_TEXT_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csv File(*.csv)|*.csv|All File(*.*)|*.*.
        /// </summary>
        internal static string FILE_FILTER {
            get {
                return ResourceManager.GetString("FILE_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.csv.
        /// </summary>
        internal static string FILE_NEM_NAME {
            get {
                return ResourceManager.GetString("FILE_NEM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input the keyword..
        /// </summary>
        internal static string MSG_ERROR_01 {
            get {
                return ResourceManager.GetString("MSG_ERROR_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify an existing folder..
        /// </summary>
        internal static string MSG_ERROR_02 {
            get {
                return ResourceManager.GetString("MSG_ERROR_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify an existing encoding..
        /// </summary>
        internal static string MSG_ERROR_03 {
            get {
                return ResourceManager.GetString("MSG_ERROR_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Regex String..
        /// </summary>
        internal static string MSG_ERROR_04 {
            get {
                return ResourceManager.GetString("MSG_ERROR_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to Save..
        /// </summary>
        internal static string MSG_ERROR_05 {
            get {
                return ResourceManager.GetString("MSG_ERROR_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csv File Saved..
        /// </summary>
        internal static string MSG_SAVED {
            get {
                return ResourceManager.GetString("MSG_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done. Found {0} Places in {1} ms..
        /// </summary>
        internal static string MSG_STATUS_FINISHED {
            get {
                return ResourceManager.GetString("MSG_STATUS_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching...    Now {0} hits.
        /// </summary>
        internal static string MSG_STATUS_RUNNING {
            get {
                return ResourceManager.GetString("MSG_STATUS_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MSG_TITLE_01 {
            get {
                return ResourceManager.GetString("MSG_TITLE_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string MSG_TITLE_02 {
            get {
                return ResourceManager.GetString("MSG_TITLE_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MSG_TITLE_03 {
            get {
                return ResourceManager.GetString("MSG_TITLE_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you like to cancel it ?.
        /// </summary>
        internal static string MSG_WARN_01 {
            get {
                return ResourceManager.GetString("MSG_WARN_01", resourceCulture);
            }
        }
    }
}
